[nonumber]
== Внимание!

В целях обеспечения возможности длительной, успешной и безопасной эксплуатации приобретённого  полного наименования изделия (далее – изделие) внимательно ознакомьтесь с настоящим паспортом и руководством по эксплуатации (далее – Документация). Соблюдение приведённых в Документации правил, ограничений и указаний (далее – Правила хранения, транспортирования и эксплуатации) продлит срок службы изделия и позволит использовать его наиболее эффективно. Нарушение Правил хранения, транспортирования и эксплуатации может привести к преждевременному прекращению гарантийных обязательств изготовителя. Начало эксплуатации приобретённого вами изделия означает безусловное согласие исполнять Правила хранения, транспортирования и эксплуатации в полном объёме. Изготовитель изделия оставляет за собой право изменять техническую спецификацию изделия без предварительного уведомления.

IMPORTANT: В целях предотвращения механических, термических или электрических повреждений изделия техническое обслуживание изделия должно производиться в соответствии с рекомендациями, указанными в Документации. В случае неисполнения указанных рекомендаций возможен выход из строя изделия по причине механических, термических или электрических повреждений. Данный случай будет являться негарантийным, т.е. изготовитель не несёт ответственности за него. Техническое обслуживание изделия изготовитель рекомендует проводить в авторизованных сервисных центрах.

NOTE: Техническое обслуживание изделия не относится к случаям бесплатного гарантийного ремонта и выполняется за отдельную плату.