
== Общие сведения об изделии

{name} – {description}.

== Сведения о сертификации

Изделие соответствует требованиям: ТР ТС 004/2011, ТР ТС 020/2011, ТР ЕАЭС 037/2016.

== Свидетельство о приёмке

Изделие серийного производства (серийный номер см. раздел 5) изготовлено и принято в соответствии с требованиями действующих технических стандартов и технических условий {code}ТУ, действующей технической документацией, обеспечивающей соответствие действующим Техническим Регламентам.

== Гарантии изготовителя

. Изготовитель гарантирует качество и безопасность изделия, а также его пригодность к эксплуатации в течение всего гарантийного срока при соблюдении покупателем Правил хранения, транспортирования и эксплуатации.
. Если иное не предусмотрено договором между изготовителем и покупателем или законодательством Российской Федерации, гарантийный срок на изделие начинает исчисляться с даты подписания покупателем документа, подтверждающего получение изделия первым покупателем (лицом, приобретшим изделие непосредственно у изготовителя), вне зависимости от количества последующих покупателей и фактов передачи изделия.
. Гарантийный срок на составные части и комплектующие изделия считается равным гарантийному сроку на само изделие, если иное не установлено в Документации. В отношении отдельных комплектующих изделия, имеющих ограниченный ресурс, устанавливается гарантия изготовителя в пределах исчерпания ресурса данных комплектующих, величина которого указана в Документации.
. Обращения в службу поддержки принимаются круглосуточно по контактным данным, указанным на сайте изготовителя <https://graviton.ru/>. Изготовитель предоставляет бесплатное консультирование по вопросам восстановления работоспособности изделия.
. Изготовитель обязуется в пределах гарантийного срока выполнять гарантийное обслуживание изделия при условии облюдения покупателем Правил хранения, транспортирования и эксплуатации.
. Гарантийными обязательствами изготовителя не покрывается риск возникновения убытков, потерь и (или) расходов, включая реальный ущерб и упущенную выгоду покупателя и иных лиц, в том числе, потери доходов, прибыли, расходов на временную замену оборудования, утраты данных и иных прямых или косвенных потерь, связанных с неисправностью изделия. Изготовитель не несёт ответственности перед покупателем и иными лицами в виде возмещения убытков, потерь и (или) расходов.
. В случае выхода изделия (отдельного устройства, агрегата, части, блока, узла) из строя в период гарантийного срока, порядок доставки изделия в авторизованный сервисный центр, либо возврат товара из авторизованного сервисного центра определяются условиями договора между изготовителем и покупателем, приобретшим изделие непосредственно у изготовителя. В случае отсутствия указанных условий порядок доставки определяется в соответствии с законодательством Российской Федерации.
. Гарантия изготовителя действует на территории Российской Федерации, если иное не предусмотрено договором между изготовителем и покупателем, приобретшим изделие непосредственно у изготовителя.

Изготовитель не несёт гарантийных обязательств в следующих случаях:

* при несоответствии серийного номера изделия, предъявляемого на гарантийное обслуживание, серийному номеру, указанному в паспорте и (или) документах, подтверждающих поставку изделия;
* при наличии явных или скрытых механических, термических и иных повреждений изделия, возникших вследствие нарушения Правил хранения, транспортирования и эксплуатации, умышленных или неосторожных действий покупателя или третьих лиц;
* если неисправность изделия возникла вследствие нарушения Правил хранения, транспортирования и эксплуатации;
* при наличии внутри корпуса изделия посторонних предметов, веществ и (или) жидкостей, независимо от их природы, если возможность подобного не оговорена в прилагаемой к изделию Документации;
* если неисправность вызвана использованием в изделии ресурсных компонентов, не рекомендованных изготовителем;y в иных случаях, определённых Документацией.

С полной версией условий гарантийного и расширенного сервисного обслуживания и информацией об авторизованных сервисных центрах можно ознакомиться на сайте изготовителя <https://graviton.ru/>.

== Основные сведения об изделии
[cols="2,3"]
|===
| Наименование изделия | 
| Модель | 
| Конфигурация | 
| Серийный номер | 
| Дата изготовления \| Гарантийный срок | 
| Комплектность | {name} pass:[<br>] Кабель питания pass:[<br>] Упаковка pass:[<br>] Руководство по эксплуатации
| Срок службы | 5 лет
| Адрес изготовителя | 121471, г.Москва, вн.тер.г.Муниципальный округ Можайский, ул.Петра Алексеева, д. 12, стр. 23, помещ. 1/1
| Телефон | 8 (800) 500-88-86
| E-mail | support@graviton.ru
| Сайт | https://graviton.ru/
2+|* Наличие определяется договором (контрактом) поставки.
|===
